name: release pdf

on:
  pull_request:
    branches: [main]
    paths: "docs/*.md"

jobs:
  build:
    name: release pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.0
      - run: pnpm install
      - name: Build pdf
        run: pnpm build:pdf
      - name: Create a draft release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.pull_request.title }}
          draft: true
          fail_on_unmatched_files: true
          files: docs/*.pdf
          name: Release ${{ github.ref }}
